### ISSUE TITLE
When images are titled 000, first 0 is trimmed off.

### ISSUE THREAD

**Issue by vaseouline** [TricksterGuy/nin10kit#26]
All of leading characters are being trimmed off in the gui viewer and in the H file as well.
This is causing problems because many of the definitions are titled the same i.e. 021.bmp and 121.bmp are now both 21.

**Comment by TricksterGuy** [comment]
Your image filenames should be named such that the filename can be a [C identifier](http://www.studytonight.com/c/keywords-and-identifier.php).  000, 121, 021 are not valid C identifiers.

Otherwise you can rename the files within the GUI (via clicking on each image), or if using the CLI --names can be used to specify the C identifier that is generated.

Working as intended.
